name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04-x86
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: git.nvduc.lab
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            git.nvduc.lab/${{ github.repository }}:${{ github.sha }}
            git.nvduc.lab/${{ github.repository }}:${{ github.ref_name }}
            git.nvduc.lab/${{ github.repository }}:latest
