name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04-x86
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses:  actions/setup-node@v6
        with:
          node-version: 20

      - name: Run npm install
        run: npm ci --no-audit

      - name: Run npm build
        run: npm run build

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            ${{ github.repository_owner }}/presentation-agent-harness:${{ github.sha }}
            ${{ github.repository_owner }}/presentation-agent-harness:${{ github.ref_name }}
